title: Page
pages: true
options:
  delete: true
  preview: true
  status: true
  template: false
  url: true
files: true
fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea